### ISSUE TITLE
Storage widget disappears preventing login

### ISSUE THREAD

**Issue by rosano** [karlb/doagain#1]
Hi Karl, it seems the storage widget appears for under a second, then goes away. Not sure why it's happening. I tried in Chrome and Firefox.

https://github.com/karlb/doagain/assets/1680612/fef705c3-5338-4363-9b58-2fcecbf2720d

**Comment by karlb** [comment]
I can confirm that the LocalStorage widget fails loading. I did not change anything in a long time, so I'm not sure yet where the breakage comes from. I'll have to take a closer look. Thanks for reporting!

**Comment by rosano** [comment]
Could be that it was attached to a container that got removed when the app loads.

**Comment by karlb** [comment]
It looks like the timing when the widget was attached was not ideal. That used to work in the past, but recent browsers seem to behave slightly differently so that the problem became apparent only recently. Could you try again now?

**Comment by rosano** [comment]
Works! Thank you for digging in.
